repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
    -   id: ruff
        args: [ --fix ]
        exclude: ^benchmarks/|^runoutput/
    -   id: ruff-format
        exclude: ^benchmarks/|^runoutput/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
        additional_dependencies: [numpy, pandas, types-setuptools, mpi4py, mtflib]
        exclude: ^benchmarks/|^runoutput/
